football_data_urls:
  EPL: https://www.football-data.co.uk/mmz4281/2324/E0.csv
  LA_LIGA: https://www.football-data.co.uk/mmz4281/2324/SP1.csv
  BUNDESLIGA: https://www.football-data.co.uk/mmz4281/2324/D1.csv
  SERIE_A: https://www.football-data.co.uk/mmz4281/2324/I1.csv
  LIGUE_1: https://www.football-data.co.uk/mmz4281/2324/F1.csv
  PTPL: https://www.football-data.co.uk/mmz4281/2324/P1.csv
